CREATE DATABASE TASK_MANAGER;

USE TASK_MANAGER;

CREATE TABLE USERINFO(
	USERID INT PRIMARY KEY AUTO_INCREMENT,
	USERNAME VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	CREATED_AT TIMESTAMP,
	LAST_ACCESS_DATE TIMESTAMP
);

INSERT INTO USERINFO(USERNAME, PASSWORD, EMAIL, CREATED_AT) VALUES("FULANO", "1234@12", "FULANO@MAIL.COM", NOW());
